[build]
command = "cd react-portfolio && npm run build"
publish = "react-portfolio/build"

[build.environment]
NODE_VERSION = "18.18.0"
CI = false

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
